[env:heltec_v3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
upload_speed = 921600
monitor_speed = 115200
build_flags =
  -DBOARD_HAS_PSRAM
  -DCORE_DEBUG_LEVEL=2
lib_deps =
  jgromes/RadioLib@^7.1.2
